- name: Disable APT auto update/installation
  hosts: all
  become: true
  tasks:
          #    - name: fix error
          #      lineinfile:
          #         path: /etc/apt/apt.conf.d/20auto-upgrades
          #         regexp: '^Update-Package-Lists "0";'
          #         state: absent

          # lineinfile은 해당 줄을 통으로 바꿔치기 한다.


    - name: disable auto update
      lineinfile:
         path: /etc/apt/apt.conf.d/20auto-upgrades
         regexp: 'APT::Periodic::Update-Package-Lists'
         line: 'APT::Periodic::Update-Package-Lists "0";'
    - name: add
      lineinfile:
         state: present
         path: /etc/apt/apt.conf.d/20auto-upgrades
         line: 'APT::Periodic::Download-Upgradeable-Packages "0";'
    - name: add
      lineinfile:
         state: present
         path: /etc/apt/apt.conf.d/20auto-upgrades
         line: 'APT::Periodic::AutocleanInterval "0";'
    - name: add
      lineinfile:
         path: /etc/apt/apt.conf.d/20auto-upgrades
         regexp: 'APT::Periodic::Unattended-Upgrade;'
         line: 'APT::Periodic::Unattended-Upgrade "0";'

