- name: install kubernetes
  hosts: all
  become: true
  tasks:
    - name: install base packages
      include: _install-base-package.yml
    - name: install docker CE
      include: _install-docker-ce.yml

    - name: install pakcages for master
      debug: msg="This will run on master "
      # 'group_names'는 시스템에서 지원하는 변수임
      when: "'k8smasters' in group_names" 


    - name: install packages for workers
      debug: msg="This will run on worker"
      # 'group_names'는 시스템에서 지원하는 변수임
      when: "'k8sworkers' in group_names"

