- name: Update and Upgrade
  hosts: all
  serial: 1
  gather_facts: false
  become: true
  tasks:
    - name: apt update
      apt: 
        update_cache: yes
    - name: apt upgrade
      apt:
        upgrade: dist
